### ISSUE TITLE
Renesas

### ISSUE THREAD

**Issue by Morvalyn** [bagel99/esl#4]
Will there be support for Renesas RL78 series? I'm interested in using clang and possibly even esl with these chips. Thank you.

**Comment by bagel99** [comment]
(Sorry this took so long, I mistakenly though issues would be emailed to me.)

Support for an architecture depends almost completely on whether LLVM supports it.  In the case of the RL78, I rather doubt they will since they don't support other 8/16 bit machines -- other than the TI MSP430, and that is not production quality.
